# Generated by Django 5.1.6 on 2025-04-10 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Employment Contract'), ('certification', 'Certification'), ('license', 'License'), ('visa', 'Visa'), ('id', 'ID/Passport'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_link', models.URLField(blank=True, help_text='Link to digital signature service (e.g., DocuSign)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
