# Generated by Django 5.1.6 on 2025-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
