# Generated by Django 5.1.4 on 2024-12-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_company_customuser_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='roll',
            new_name='role',
        ),
    ]
