# Generated by Django 5.1.6 on 2025-04-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_created_company_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ceo', 'CEO'), ('team_lead', 'Team Lead'), ('employee', 'Employee'), ('hr', 'HR')], default='employee', max_length=20),
        ),
    ]
