# Generated by Django 5.1.6 on 2025-04-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0001_initial'),
        ('project_management', '0003_task_image_task_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='project_management.project'),
        ),
    ]
